### ISSUE TITLE
Built-in support for common programs

### ISSUE THREAD

**Issue by lunjon** [lunjon/dotfiles#2]
Add support for tracking known configurations, such as git and vim.

## How

Add new section, with a good name, to dotfile:

```toml
[known]
git = true # simplest form
neovim = { ignore = ["*.txt"] } # table form
```

The idea is to make it easier to track known configurations cross-platform (see #3).
