### ISSUE TITLE
Additional sections for easier tracking

### ISSUE THREAD

**Issue by lunjon** [lunjon/dotfiles#3]
Add sections that correspond to well-known directories:
- Configuration file standard locations: `config`
  - Linux: `$XDG_CONFIG_HOME` or `$HOME/.config`
  - Windows: `{FOLDERID_RoamingAppData}`
  - MacOS: `$HOME/Library/Application Support`
- Local binaries (Linux only): `binary`
  - `$XDG_BIN_HOME` or `$HOME/.local/bin`

```toml
[config] 
starship = "starship.toml"

[binary]
my_script = "myscript.sh" # ~/.local/bin/myscript.sh
```

## Implementation status

- ~config~ (#4)
- data
- binary
